### ISSUE TITLE
This should explicitly request a "Ed25519Signature2020" proof

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/di-ed25519-test-suite#4]
The VC API has a `type` option to request a certain proof type:
https://github.com/w3c-ccg/vc-api/blob/main/components/IssueCredentialOptions.yml#L20

The VC API should send this option with a `Ed25519Signature2020` value.

Potentially the test suite could also allow implementations to use the `verificationMethod` option:
https://github.com/w3c-ccg/vc-api/blob/main/components/IssueCredentialOptions.yml#L23

Without that, the assumption is that a "default verification method" will be used, also see discussion here:
https://github.com/w3c-ccg/vc-api/issues/67

**Comment by OR13** [comment]
https://github.com/w3c-ccg/traceability-interop/tree/main/docs/tutorials/agility

**Comment by msporny** [comment]
Agreed, this should be fixed.

**Comment by aljones15** [comment]
I will get on this once I get back and sorry about missing this.

**Comment by aljones15** [comment]
closing this as `type` is no longer an issuer option.
